name: Android Release CI

on:
  push:
    tags:
      - 'v*'    # Only runs when you push a version tag like v1.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build Release APK
        run: ./gradlew assembleRelease

      - name: Upload Release APK
        uses: softprops/action-gh-release@v1
        with:
          files: app/build/outputs/apk/release/*.apk
